config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :registrations
    root to: "registrations#index"    
  end

  scope "/:locale", locale: /en|zh-CN/ do
    resource :registration, only: [ :new, :edit, :create, :update ]
    get "/:id" => "high_voltage/pages#show", :as => :page, :format => false
  end

  root to: redirect("/zh-CN/index")

end

app/models/registration.rb
class Registration < ActiveRecord::Base

  validates_presence_of :email, :payment_type
  validates_presence_of :full_name, :first_name, :family_name, allow_nil: true
  validates_presence_of :profession
  validates_presence_of :invoice_needed
  validates_presence_of :invoice_title, if: -> (record) { record.invoice_needed == "invoice" }
  validates_presence_of :section_type, if: -> (record) { record.profession == "employee" }

  # validates_uniqueness_of :email

  before_save :generate_full_name

  default_scope -> { where.not(hidden: true) }

  def generate_full_name
    self.full_name ||= "#{first_name} #{family_name}"
  end

end

app/models/setting.rb
class Setting < RailsSettings::CachedSettings
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  USERNAME, PASSWORD = Setting.admin_username, Setting.admin_password

  before_action :authenticate
  layout "admin"

  private

    def authenticate
      authenticate_or_request_with_http_basic do |username, password|
        username == USERNAME && password == PASSWORD
      end
    end

    def set_locale
      I18n.locale = :"zh-CN"
    end

end

app/controllers/admin/registrations_controller.rb
class Admin::RegistrationsController < Admin::ApplicationController
  require 'csv'

  def index
    @registrations = Registration.all

    @attributes = %i(id full_name affiliation profession title address postcode phone email section_type payment_type invoice_title created_at request)
    @listed_attributes = %i(full_name profession title phone email section_type payment_type)
    @detailed_attributes = @attributes
    @translate_attributes = %i(profession title section_type payment_type)
    @data = Hash[ @registrations.map do |registration|
      [ registration.id, Hash[ @attributes.map do |attribute|
        attr_value = registration.send(attribute)
        [ attribute,
          if @translate_attributes.include?(attribute)
            attr_value.blank? ? nil : t(attr_value, scope: "activerecord.attributes.registration/#{attribute}", default: attr_value)
          else
            attr_value.is_a?(Time) ? l(attr_value) : attr_value
          end ]
      end ] ]
    end ]

    respond_to do |format|
      format.html
      format.csv do
        send_data(render_to_string)
      end
      format.xls do
        send_data(render_to_string)
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale

  private
  
    def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @registration = Registration.new
  end

  def create
    @registration = Registration.new(registration_params)
    if @registration.save
      flash[:info] = t(:success, scope: "registration/new")
      redirect_to page_path(id: :registration)
    else
      render "new"
    end
  end

  protected

    def registration_params
      params.require(:registration).permit(%i(first_name family_name \
        full_name profession title address postcode phone email \
        section_type payment_type invoice_title invoice_needed affiliation request))
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def dash_nobr text
    text.split(" ").map do |word|
      word.include?("-") ? "<nobr>#{word}</nobr>" : word
    end.join(" ").html_safe
  end

  def active? id
    params[:id].split("/")[0] == id.to_s
  end

  def locale? locale
    params[:locale] == locale.to_s
  end

  def english_path options = {}
    url_for(options.merge(locale: :en))
  end

  def chinese_path options = {}
    url_for(options.merge(locale: :"zh-CN"))
  end

  def secure_path options = {}
    request.original_url.sub("http://", "https://")
  end

  def t key, options = {}
    I18n.t(key, options.reverse_merge(scope: params[:id]))
  end

  def bootstrap_text_field f, attribute, options = {}
    klass = f.object.class
    human_attribute_name = klass.human_attribute_name(attribute)
    ret = <<-EOF
      <div class="form-group #{"has-error" if f.object.errors.any? && f.object.errors[attribute].any?}">
        <label for="registration_#{attribute}" class="col-sm-4 control-label">
          #{human_attribute_name}
        </label>
        <div class="col-sm-8">
          #{f.text_field(attribute, class: "form-control", placeholder: human_attribute_name)}
    EOF
    ret << "#{"<p class=\"help-block\">#{options[:tips]}</p>"}" if options[:tips]
    ret << <<-EOF
        </div>
      </div>
    EOF
    ret.html_safe
  end

  def bootstrap_text_area f, attribute, placeholder = nil, options = {}
    klass = f.object.class
    human_attribute_name = klass.human_attribute_name(attribute)
    ret = <<-EOF
      <div class="form-group #{"has-error" if f.object.errors.any? && f.object.errors[attribute].any?}">
        <label for="registration_#{attribute}" class="col-sm-4 control-label">
          #{human_attribute_name}
        </label>
        <div class="col-sm-8">
          #{f.text_area(attribute, class: "form-control", placeholder: placeholder||human_attribute_name, rows: 4)}
    EOF
    ret << "#{"<p class=\"help-block\">#{options[:tips]}</p>"}" if options[:tips]
    ret << <<-EOF
        </div>
      </div>
    EOF
    ret.html_safe
  end

  def bootstrap_password_field f, attribute, options = {}
    klass = f.object.class
    human_attribute_name = klass.human_attribute_name(attribute)
    ret = <<-EOF
      <div class="form-group">
        <label for="registration_#{attribute}" class="col-sm-4 control-label">
          #{human_attribute_name}
        </label>
        <div class="col-sm-8">
          #{f.password_field(attribute, class: "form-control", placeholder: human_attribute_name)}
        </div>
      </div>
    EOF
    ret.html_safe
  end

  def bootstrap_radio_buttons f, attribute, buttons, options = {}
    klass = f.object.class
    human_attribute_name = klass.human_attribute_name(attribute)
    ret = <<-EOF
      <div class="form-group #{"has-error" if f.object.errors.any? && f.object.errors[attribute].any?}">
        <label for="registration_#{attribute}" class="col-sm-4 control-label">
          #{human_attribute_name}
        </label>
        <div class="col-sm-8 checkbox">
    EOF
    buttons.each do |button|
      ret << <<-EOF
        <label>
          #{f.radio_button(attribute, button)}
          #{klass.human_attribute_name("#{attribute}.#{button}")}
        </label>
      EOF
    end
    ret << "#{"<p class=\"help-block\">#{options[:tips]}</p>"}" if options[:tips]
    ret << <<-EOF
        </div>
      </div>
    EOF
    ret.html_safe
  end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <title>Panda Course Admin</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'admin', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag  "html5shiv.min" %>
    <%= javascript_include_tag  "respond.min" %>
  <![endif]-->
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <title>Panda Course 2015</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag  "html5shiv.min" %>
    <%= javascript_include_tag  "respond.min" %>
  <![endif]-->
</head>
<body>

  <header class="masthead <%= active?("index") ? "jumbotron" : "well"  %>">
    <div class="container">
      <h2><%= t "subtitle", scope: :layout %></h2>
      <h1><%= t "title", scope: :layout %></h1>
      <p>
        <%= t "location", scope: :layout %>
        &nbsp;&nbsp;
        <%= t "time", scope: :layout %>
      </p>
    </div>
    <div class="right-top">
      <div class="languages">
        Language:
        <a <%= raw locale?(:en) ? "class=\"active\"" : "href=\"#{english_path}\"" %>>English</a>
        |
        <a <%= raw locale?(:"zh-CN") ? "class=\"active\"" : "href=\"#{chinese_path}\"" %>>简体中文</a>
        |
        <a class="active" href="<%= secure_path %>"><%= t "secure", scope: :layout %></a>
      </div>
      <div class="weixin hidden-xs">
        <%= t(:wechat, scope: :layout) %><br>
        <%= image_tag "images/QR.png", width: 75 %>

        <%= image_tag "images/QR.png", class: "qrcode bounceIn animated", width: 300 %>
      </div>
    </div>
  </header>

  <div class="container">
    <nav class="navbar navbar-default" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= page_path(id: :index) %>">PANDA 2015</a>
      </div>

      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav">
          <% t("navbar", scope: :layout).each do |key, value| %>
            <li <%= raw "class=\"active\"" if active? key %>><%= link_to value, page_path(id: key) %></li>
          <% end %>
          <% if locale?(:en) %>
            <li><a href="/2014/en/index.html">PANDA2014</a></li>
            <li><a href="/2013/index.html">PANDA2013</a></li>
          <% elsif locale?(:"zh-CN") %>
            <li><a href="/2014/index.html">PANDA2014</a></li>
            <li><a href="/2013/indexC.html">PANDA2013</a></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %> alert-dismissible">
        <button type="button" class="close" data-dismiss="alert"><span>&times;</span><span class="sr-only">Close</span></button>
        <%= value %>
      </div>
    <% end %>

    <%= yield %>

  </div>

  <footer class="footer">
    <div class="container">
      <p class="text-muted">Designed and built with <a href="http://getbootstrap.com/" target="_blank">Twitter Bootstrap</a>.</p>
    </div>
  </footer>

</body>
</html>

app/views/pages/_to_be_announced.html.erb
<div class="jumbotron">
  <h2><%= t :title, scope: :to_be_announced %></h2>
  <%= link_to t(:button, scope: :to_be_announced), page_path(id: :index), class: "pull-right" %>
</div>

app/views/pages/accommodations.html.erb
<div class="map-wrapper">
  <div id="map"></div>

  <div class="content">
    <h4 class="ml20 mb20"><%= t(:title) %></h4>
    <ol class="ml20">
      <% t(:list).each_with_index do |list, index| %>
        <li>
          <h4><%= list[:title] %> <a class="mt0 btn btn-primary btn-xs" href="javascript: show(<%= index %>);"><span class="glyphicon glyphicon-map-marker"></span><%= t(:map) %></a></h4>
          <%= simple_format list[:para] %>
        </li>
      <% end %>
    </ol>
  </div>
</div>

<script type="text/javascript">
  <% geoData = [] %>
  <% t(:list).each do |list| %>
    <% geoData.push({
      position: list[:position],
      title: list[:title],
      content: ("<h4>#{list[:title]}</h4>#{simple_format(list[:para])}")
    }) %>
  <% end %>

  var geoData = <%= raw geoData.to_json %>;
  var geoCenter = {
    "lat": <%= geoData.map{|info|info[:position][:lat]}.reduce(&:+) / geoData.length %>,
    "lng": <%= geoData.map{|info|info[:position][:lng]}.reduce(&:+) / geoData.length - 0.01 %>
  };
</script>

<%# if params[:locale] == "en" %>
<!--   <script type="text/javascript" src="//maps.googleapis.com/maps/api/js?key=AIzaSyC81D29r_jCs93QwACNyW6BC_nBjU8mSAk&amp;sensor=false"></script>
  <script type="text/javascript">
    var markers = [];

    function initialize() {
      var center = new google.maps.LatLng(geoCenter["lat"], geoCenter["lng"]);

      var map = new google.maps.Map(document.getElementById('map'), {
        disableDefaultUI: true,
        center: center,
        zoom: 15
      });

      var infowindow = new google.maps.InfoWindow();

      for (var i = 0; i < geoData.length; i++) {
        var marker = new google.maps.Marker({
          map: map,
          content: geoData[i].content,
          position: new google.maps.LatLng(geoData[i].position.lat, geoData[i].position.lng)
        });

        google.maps.event.addListener(marker, 'click', function() {
          infowindow.setContent(this.content);
          infowindow.open(map, this);
        });

        markers.push(marker);
      }
    }

    function show(i) {
      google.maps.event.trigger(markers[i], 'click');
    }

    $(document).ready(initialize);
  </script> -->
<%# else %>
  <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&amp;ak=E5072c8281660dfc534548f8fda2be11"></script>
  <script type="text/javascript">
    var local;

    function initialize() {
      // 百度地图API功能
      var map = new BMap.Map("map");            // 创建Map实例
      map.enableScrollWheelZoom(true);
      local = new BMap.LocalSearch(map, {renderOptions: {map: map}, pageCapacity: 1});
      local.search(geoData[0].title);
    }

    function show(id) {
      local.search(geoData[id].title)
    }

    $(document).ready(initialize);
  </script>
<%# end %>

app/views/pages/committee.html.erb
<% t("panel").each do |panel| %>
  <div class="well">
    <div class="row">
      <div class="col-md-3">
        <h3 class="sm-except-text-right ml20"><%= dash_nobr panel[:title] %></h3>
      </div>
      <div class="col-md-9">
        <ul class="mt20 mb20">
          <% panel[:list].each do |list| %>
            <li><p><%= raw list %></p></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/pages/contact.html.erb
<div class="padded">
  <h4 class="text-muted"><%= t :para %></h4>
</div>
<div class="row">
  <% panels = t("panel").each_slice(2).to_a.transpose %>
  <% panels.each do |panels_slice| %>
    <div class="col-md-6">
      <% panels_slice.each do |panel| %>
        <div class="well">
          <h3 class="ml20 mb30"><%= panel[:title] %> <small><%= panel[:subtitle] %></small></h3>
          <ul class="ml20">
            <% panel[:list].each do |list| %>
              <li><p><%= raw list %></p></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  <% end %>
  <div class="col-md-6">
    <div class="well">
      <div class="row">
        <div class="col-md-7">
          <h4 class="ml20 mt30"><%= raw t :weixin %></h4>
        </div>
        <%= image_tag "images/QR.png", class: "col-md-5" %>
      </div>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="col-md-7">
      <h2><%= t "jumbotron.title" %></h2>
      <p><%= raw t "jumbotron.para" %></p>
      <a href="<%= t "jumbotron.button.link" %>" class="btn btn-lg btn-warning"><%= t "jumbotron.button.title" %> »</a>
    </div>

    <div class="col-md-5">
      <%= image_tag "images/index.jpg", class: "img-thumbnail img-tilt" %>
    </div>
  </div>
</div>

<div class="row">
  <% t("media").each do |item| %>
    <div class="col-sm-4">
      <div class="media">
        <div class="row">
          <div class="media-img pull-left col-sm-5 col-md-4">
            <%= image_tag item[:image] %>
          </div>
          <div class="media-body col-sm-7 col-md-8">
            <h4 class="media-heading"><%= item[:title] %></h4>
            <p class="hidden-sm"><%= item[:para] %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/program.html.erb
<% t(:session).each do |session| %>
  <% if session[:title] %>
    <h3 class="mt30 ml50"><%= session[:title] %></h3>
  <% end %>
  <% session[:panel].each do |panel| %>
    <div class="well">
      <div class="row">
        <div class="col-md-3">
          <% if panel[:title] %>
            <h3 class="sm-except-text-right ml20"><%= dash_nobr panel[:title] %></h3>
          <% end %>
        </div>
        <div class="col-md-9">
          <ul class="mt20 mb20">
            <% panel[:list].each do |list| %>
              <li><p><%= raw list %></p></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/pages/registration.html.erb
<div class="jumbotron">
  <p><%= t :para %></p>

  <h3><%= t :subtitle %></h3>

  <span><%= raw t :description %></span>

  <div class="row">
    <div class="col-md-6">
      <table class="table">
        <% table = t(:table).dup %>
        <% thead = table.shift %>
        <thead>
          <tr>
            <% thead.each do |th| %>
              <th><%= th %></th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% table.each do |tr| %>
            <tr>
              <% tr.each do |td| %>
                <td><%= raw td %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <em class="text-muted"><%= raw t :para2 %></em>
  <br>

  <%= link_to "#{t(:button)} »", new_registration_path, class: "btn btn-lg btn-warning" %>
</div>

app/views/pages/speakers.html.erb
<div class="row">
  <div class="col-md-12">
    <% t("well").each do |well| %>
      <div class="well speaker">
        <%= image_tag well[:image], class: "img-thumbnail pull-left" if well[:image].present? %>
        <h2><%= well[:title] %> <small><%= well[:subtitle] %></small></h2>
        <p><%= simple_format well[:para] %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/sponsors.html.erb
<div class="jumbotron sponsors">
  <p><%= t :para %></p>

  <div class="row">
    <% t(:panel).each do |panel| %>
      <div class="col-md-<%= panel[:width] %>">
        <% if panel[:title] %>
          <h3><%= panel[:title] %></h3>
        <% end %>
        <p>
          <% panel[:list].each do |item| %>
            <a href="<%= item[:url] %>">
              <%= image_tag item[:image] %>
            </a>
          <% end %>
        </p>
      </div>
    <% end %>
  </div>

</div>

app/views/pages/stipend.html.erb
<div class="jumbotron">
  <h3 class="mb20">Riscure优秀学生奖学金（2位）</h3>
  <p>
    作为PANDA的赞助商，Riscure将提供两份优秀学生奖学金。
    Riscure将为奖学金获得者报销注册费、差旅及住宿费用。所有高校、科研机构的全职硕士、博士生都可以申请。
  </p>
  <p>
    请在10月11日（北京时间23:59）前将学生证照片、个人简历和研究方向（英语）、申请理由（英语，并附带导师签字）发送到以下邮件：<a href="mailto:fanjunfeng@gmail.com">fanjunfeng@gmail.com</a>（抄送：marzec@riscure.com）
  </p>
  <p>
    Riscure将在北京时间2014年10月15日前通过邮件通知遴选结果。
  </p>
  <em class="text-muted">Riscure对奖学金事务具有最终解释权。</em>
</div>

app/views/pages/venue.html.erb
<div class="map-wrapper">
  <div id="map"></div>

  <div class="content">
    <ul class="mt30 ml20">
      <% t(:list).each_with_index do |list, index| %>
        <li>
          <h4><%= list[:title] %></h4>
          <%= simple_format list[:para] %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<% if params[:locale] == "en" %>
  <script type="text/javascript" src="//maps.googleapis.com/maps/api/js?key=AIzaSyC81D29r_jCs93QwACNyW6BC_nBjU8mSAk&amp;sensor=false"></script>
  <script type="text/javascript">
    function initialize() {
      var map = new google.maps.Map(document.getElementById('map'), {
        disableDefaultUI: true,
        center: new google.maps.LatLng(<%= t(:position)[:lat] %>, <%= t(:position)[:lng] - 0.01 %>),
        zoom: 15
      });

      var infowindow = new google.maps.InfoWindow();

      var marker = new google.maps.Marker({
        map: map,
        content: "<%= raw t(:position)[:content] %>",
        position: new google.maps.LatLng(<%= t(:position)[:lat] %>, <%= t(:position)[:lng] %>)
      });

      google.maps.event.addListener(marker, 'click', function() {
        infowindow.setContent(this.content);
        infowindow.open(map, this);
      });
      google.maps.event.trigger(marker, 'click');
    }

    $(document).ready(initialize);
  </script>
<% else %>
  <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&amp;ak=E5072c8281660dfc534548f8fda2be11"></script>
  <script type="text/javascript">

    function initialize() {
      // 百度地图API功能
      var map = new BMap.Map("map");
      var point = new BMap.Point(<%= t(:position)[:lat] %>, <%= t(:position)[:lng] %>);
      var marker = new BMap.Marker(point);  // 创建标注
      map.addOverlay(marker);  // 将标注添加到地图中
      map.centerAndZoom(new BMap.Point(<%= t(:position)[:lat] %> - 0.002, <%= t(:position)[:lng] %>), 18);
      var opts = {
        width : 200,     // 信息窗口宽度
        height: 100,     // 信息窗口高度
      }
      var infoWindow = new BMap.InfoWindow("<%= raw t(:position)[:content] %>", opts);  // 创建信息窗口对象
      marker.addEventListener("click", function() {
        map.openInfoWindow(infoWindow, point); //开启信息窗口
      });
      map.openInfoWindow(infoWindow, point);
    }

    $(document).ready(initialize);
  </script>
<% end %>